sudo: false
language: rust

cache:
  cargo: true
  directories:
    - $HOME/gcc-arm-none-eabi-6_2-2016q4

os:
  - linux
  - osx

# If you change this, you must also change README and Common.mk
rust:
  - nightly-2017-05-24

before_install:
  # Install Homebrew on Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)";
      export PATH="$PATH:$HOME/.linuxbrew/bin";
    fi
  # Update homebrew
  - brew tap ARMmbed/homebrew-formulae
  - brew update
  # Install needed packages
  - brew install arm-none-eabi-gcc

before_script:
  - (cargo install --vers 0.7.1 rustfmt || true)
  - (cargo install xargo || true)
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] || [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then npm install -g markdown-toc; fi

script:
  - command -v arm-none-eabi-gcc && echo yep || echo nope
  - export PATH=$HOME/.cargo/bin:$PATH
  - export PATH="$PATH:$HOME/.linuxbrew/bin";
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] || [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then tools/run_cargo_fmt.sh diff; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] || [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then make allboards; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] || [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then pushd userland/examples && ./build_all.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] || [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then popd && tools/toc.sh; fi

